### ISSUE TITLE
Restructure the examples as an individual packages

### ISSUE THREAD

**Issue by bailaC** [ros-controls/ros2_control_demos#119]
Hello All, 

while working with examples, I found it would be better if we 

1. Keep individual examples complete in itself.
2. Each example should contain the proper folder structure
3. While merging any Pull Request, it **MUST** have the **Readme** file, which **MUST** include below points but not limited to,
- How to run the example (Detailed step)
- Expected command output (if any)
- Expected simulation output (rviz, Gazebo etc. if any)

The basic idea behind all the above points is,
1. Any example can be tried independently.
2. All the required files/folders will be inside a "Single" folder. Users need not to concern about any other files/folders.
3. Maintenance will be much cleaner.

These are just my thoughts. Just want to make life easier for the Beginners. Please feel free to add your thoughts.

**Comment by destogl** [comment]
Everything is placed into #231
