### ISSUE TITLE
[Question about the examples] Where is an Actuator example?

### ISSUE THREAD

**Issue by pepeRossRobotics** [ros-controls/ros2_control_demos#145]
Hello,

I am writing a HW interface for an actuator. I want it to be minimal and start building from it. By checking the examples, it seems that every example is using the `hardware_interface::SystemInterface` and use this to read/write to the hardware.
But I cannot find any `hardware_interface::ActuatorInterface` nor `hardware_interface::SensorInterface`. Am I missing something? Are the implementations of these trivial enough to derive them from the System interface examples?

Best,
Pepe

**Comment by destogl** [comment]
There is one `SensorInterface` example (at least now). As of actuator, it is missing, but all is equivalent.

If you are starting writing driver, check control.ros.org for details. There is also a reference to scripts for code-generation of minimal examples/packages.
