### ISSUE TITLE
Is there any example for lidar sensor on ROS2 control hardware component?

### ISSUE THREAD

**Issue by MikeyYen** [ros-controls/ros2_control_demos#146]
Hi All

Currently, I'm working on developing lidar hardware component.
Is there any example for that?

Thanks

**Comment by destogl** [comment]
Hi @MikeyYen,

Currently we don't have any example like that. Did you do something already? Maybe we can discuss how to integrate it.

Cheers,

Denis

**Comment by olivier-stasse** [comment]
Closing this issue because it has been hanging around for quite some time. Feel free to reopen if needed.
