### ISSUE TITLE
diffbot not circling in Rviz 

### ISSUE THREAD

**Issue by HusamZain** [ros-controls/ros2_control_demos#153]
I'm using ROS2 galactic , and trying to do the diffbot example.
I downloaded ros2-control and ros2-controllers from apt not source 
everything seems to work fine, until when I try to write a message to /cmd_vel  as in step 5 (see first pic)nothing happen and the robot in rviz doesn't circling.
![Screenshot from 2022-03-09 16-48-22](https://user-images.githubusercontent.com/97671800/157477711-7cb01e2e-3d67-4b73-be6b-1b2e90d6ffe1.png)

I checked the topics , and this is what I found 
![Screenshot from 2022-03-09 16-50-41](https://user-images.githubusercontent.com/97671800/157477942-5688ff4b-62b4-45ce-a43c-cee6a56a2c99.png)
so I wrote to the /diffbot_base_controller/cmd_vel_unstamped , 
`ros2 topic pub --rate 30 diffbot_base_controller/cmd_vel_unstamped  geometry_msgs/msg/Twist "linear:
 x: 0.7
 y: 0.0
 z: 0.0
angular:
 x: 0.0
 y: 0.0
 z: 1.0"`

and the robot started circling, so is that means the command from you wrong and it should be `diffbot_base_controller/cmd_vel_unstamped ` instead of `/cmd_vel` ? or I did something wrong ?

**Comment by destogl** [comment]
You did all good. Probably the documentation is not on the newest state. Can you please open PR with your fix?

**Comment by HusamZain** [comment]
@destogl 
Thank you for your feedback! 
Yes sure, I'm new to github, so not sure if I did it right !

**Comment by be-glass** [comment]
It would be very nice to place a warning in the documentation. It took me two 2 days of debugging before I found this.
