### ISSUE TITLE
open_loop flag is used differently in rrbot vs diffbot

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control_demos#175]
`open_loop_control: true` vs `open_loop: true`

https://github.com/ros-controls/ros2_control_demos/blob/master/ros2_control_demo_bringup/config/rrbot_controllers.yaml#L39
https://github.com/ros-controls/ros2_control_demos/blob/master/ros2_control_demo_bringup/config/diffbot_controllers.yaml

**Comment by destogl** [comment]
Closing this because it is actually an issue with controllers.
