### ISSUE TITLE
ros2 control demos foxy related packages NOT WORKNG

### ISSUE THREAD

**Issue by enriLoniterp** [ros-controls/ros2_control_demos#202]
hi everbody,

i was searching for related packages of ROS2 Foxy version in main git hub page in the README and when clickin on related packages i got
![183417192-5743a997-310b-42a2-9729-cb3f524dc4e7](https://user-images.githubusercontent.com/43698855/183419081-998321b6-6dac-4e7c-a303-197a898779db.png)
![183417200-8253fa5b-e7f2-404e-a654-fc1f81cb529c](https://user-images.githubusercontent.com/43698855/183419095-1fb0f3bc-f0d1-41a1-9b6d-7b23c065cd52.png)

**Comment by bmagyar** [comment]
Nice picture

**Comment by destogl** [comment]
The package is not release so you will not find it in ros-index for now.
