### ISSUE TITLE
change hw_state_ to hw_position for only position command rrbot. 

### ISSUE THREAD

**Issue by benthebear93** [ros-controls/ros2_control_demos#209]
As a beginner, i been reading code for rrbot and diffbot together.

One thing that made me little confusing was variable's name. 

variable for state of position only rrbot is 

`std::vector<double> hw_states_;`

variable for diffbot is

```
  std::vector<double> hw_positions_;
  std::vector<double> hw_velocities_;

```
and rrbot_system_multi_interface has

```
  std::vector<double> hw_states_positions_;
  std::vector<double> hw_states_velocities_;
  std::vector<double> hw_states_accelerations_;
```

it's trivial but wouldn't it be better to unify the names of variables?

**Comment by bmagyar** [comment]
Such suggestions are best communicated through PRs ;)

**Comment by benthebear93** [comment]
@bmagyar I will think about more general ways to unify the variables name and do the PR.

**Comment by destogl** [comment]
@benthebear93 are you working on this, or should we close the issue?

**Comment by destogl** [comment]
Closing since it is stale...
