### ISSUE TITLE
contact service /controller_manager/load_controller 

### ISSUE THREAD

**Issue by bakirbbm** [ros-controls/ros2_control_demos#214]
when i run my launch file : ros2 launch yass_description launch_sim.launch.py
PS : i try the same code the past week and every thing was okay 
i forget the last week like i said the launch file was normally work but before i launch the launch file i was firstly i launch gazebo server manually by this `ros2 launch gazebo_ros gzserver.launch.py`
i get this error 
`
[INFO] [launch]: All log files can be found below /home/bakir/.ros/log/2022-12-08-21-47-16-356515-bakir-31434
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [gzserver-1]: process started with pid [31435]
[INFO] [gzclient-2]: process started with pid [31437]
[INFO] [robot_state_publisher-3]: process started with pid [31439]
[INFO] [spawn_entity.py-4]: process started with pid [31441]
[robot_state_publisher-3] Link chassis had 3 children
[robot_state_publisher-3] Link camera_link had 1 children
[robot_state_publisher-3] Link camera_link_optical had 0 children
[robot_state_publisher-3] Link caster_wheel had 0 children
[robot_state_publisher-3] Link laser_frame had 0 children
[robot_state_publisher-3] Link left_wheel had 0 children
[robot_state_publisher-3] Link right_wheel had 0 children
[robot_state_publisher-3] [INFO] [1670532439.275094272] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1670532439.276391190] [robot_state_publisher]: got segment camera_link
[robot_state_publisher-3] [INFO] [1670532439.276466972] [robot_state_publisher]: got segment camera_link_optical
[robot_state_publisher-3] [INFO] [1670532439.276511764] [robot_state_publisher]: got segment caster_wheel
[robot_state_publisher-3] [INFO] [1670532439.276546880] [robot_state_publisher]: got segment chassis
[robot_state_publisher-3] [INFO] [1670532439.276582165] [robot_state_publisher]: got segment laser_frame
[robot_state_publisher-3] [INFO] [1670532439.276619167] [robot_state_publisher]: got segment left_wheel
[robot_state_publisher-3] [INFO] [1670532439.276655215] [robot_state_publisher]: got segment right_wheel
[spawn_entity.py-4] [INFO] [1670532441.504195779] [spawn_entity]: Spawn Entity started
[spawn_entity.py-4] [INFO] [1670532441.512939750] [spawn_entity]: Loading entity published on topic /robot_description
[spawn_entity.py-4] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-4]   warnings.warn(
[spawn_entity.py-4] [INFO] [1670532441.540668685] [spawn_entity]: Waiting for entity xml on /robot_description
[spawn_entity.py-4] [INFO] [1670532442.305614442] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-4] [INFO] [1670532442.314110482] [spawn_entity]: Waiting for service /spawn_entity
[spawn_entity.py-4] [INFO] [1670532445.398296029] [spawn_entity]: Calling service /spawn_entity
[gzserver-1] [INFO] [1670532449.102033277] [camera_controller]: Publishing camera info to [/camera/camera_info]
[spawn_entity.py-4] [INFO] [1670532449.182340765] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [myboot]
[INFO] [spawn_entity.py-4]: process has finished cleanly [pid 31441]
[INFO] [ros2-5]: process started with pid [31545]
[ros2-5] Could not contact service /controller_manager/load_controller
[ERROR] [ros2-5]: process has died [pid 31545, exit code 1, cmd 'ros2 control load_controller --set-state active joint_state_broadcaster'].
[INFO] [ros2-6]: process started with pid [31598]
[ros2-6] Could not contact service /controller_manager/load_controller
[ERROR] [ros2-6]: process has died [pid 31598, exit code 1, cmd 'ros2 control load_controller --set-state active diff_drive_base_controller'].
`

so i think the error was in causes of late to contact service /controller_manager/load_controller
if you need any additional information i will give it for you 
may laptop in think-pad i5-5300u with 8gb in RAM i have no graphic card

**Comment by bmagyar** [comment]
I suggest you look at how we do things in ros2_control_demos and check your launch files and URDFs against those examples
