### ISSUE TITLE
How to apply transmission gear ratio (mechanical_reduction) in hardware_interface

### ISSUE THREAD

**Issue by firesurfer** [ros-controls/ros2_control_demos#216]
I have a transmission which looks like this:

```
<transmission name="${prefix}transmission/${name}">
          <plugin>transmission_interface/SimpleTransmission</plugin>
          <joint name="${name}" role="${prefix}${name}_actuator">
            <mechanical_reduction>${1.0 / config.travel_per_revolution}</mechanical_reduction>
          </joint>
        </transmission>
```

When writing a hardware interface i can access the via the `hardware_interface::HardwareInfo &system_info` passed in the `on_init` method. 

Unfortunately I couldnt find any examples for best practices on how to actually use the transmission. My idea was to simply store a list in the hardware interface with the mechanical reduction for each joint handled by the hw interface and apply this value when calling write/read.

Is this the intended usage or am I doing this completely wrong?

**Comment by firesurfer** [comment]
Still looking for an answer :)

**Comment by olivier-stasse** [comment]
Dear @firesurfer, you should probably ask this question in the [ros2_control](https://github.com/ros-controls/ros2_control) repository where ```hardware_interface``` are defined. or in the [gz_ros2_control](https://github.com/ros-controls/gz_ros2_control) repository.

At the ```hardware_interface``` level, I have seen often the transmission used to hide a mechanical differential mechanism and provides an interface to an equivalent serial controlled hardware. This simplify the user experience. At the simulator side, the transmissison information is often used to avoid having a complete mechanical model and simplify the relation ship between the control value and the joint value (typically to emulate a reduction gear). In the latter case, you should check with the simulator plugin (gz_ros2_control or gazebo_ros2_control) if this is correct.

**Comment by firesurfer** [comment]
@olivier-stasse  Thanks a lot for your answer I posted the question also in the main ros2_control repo (https://github.com/ros-controls/ros2_control/issues/897)

**Comment by jordan-palacios** [comment]
Hey @firesurfer, if you are still interested, you can check the demo I've been working on in #226. Any feedback is appreciated.

**Comment by firesurfer** [comment]
@jordan-palacios  Thanks a lot this is exactly what I was looking for !
