### ISSUE TITLE
Link in the Description not working 

### ISSUE THREAD

**Issue by jaronski** [ros-controls/ros2_control_demos#217]
Hi all,
the link https://github.com/ros-controls/gazebo_ros_demos/tree/ahcorde/port/ros2 is not working. Would it be possible to fix that as i would like to check out?

Thanks
Jaronski

**Comment by christophfroehlich** [comment]
Hi, are you sure that this is part of ros2_control_demos? I'm finding this link only in the readme of [gazebo_ros2_control repo](https://github.com/ros-controls/gazebo_ros2_control#gazebo--moveit2--ros-2)..
