### ISSUE TITLE
Use case for a simple DIY robot 

### ISSUE THREAD

**Issue by olivier-stasse** [ros-controls/ros2_control_demos#22]
The goal of this use case is to show how easily ROS can help robot makers.

Several discussions with people from FabLabs show that they do not know where to start.
Making a clear, lean example would be *very* helpful.

Maybe this is more about documentation, but it could show clearly where to put the real-time process, the access to the electronics to read sensors, call controllers and write the command.

Then briefly show in the documentation how all the functionalities visualization, playing back trajectories and planning are coming from free. 

This could be nice for a  PhD student making his own robot prototype.

**Comment by Kakcalu13** [comment]
Please...I need this lol

**Comment by destogl** [comment]
done in example 1
