### ISSUE TITLE
Error when compiling packages with underlaying system packages

### ISSUE THREAD

**Issue by AmmarAlbakri** [ros-controls/ros2_control_demos#227]
I have a foxy installation with control controllers and the related packages, I would like to clone this repo and run it on my machine so I followed the guide for setup and cloned the required packages and installed dependencies with rosdep.
When I am trying to build the packages I am getting a warning: 
`WARNING:colcon.colcon_core.package_selection:Some selected packages are already built in one or more underlay workspaces`
I guess this is breaking or anything but after that when it comes to building the hardware_interface package I get a ton of errors:
`demos_ws/src/ros2_control/hardware_interface/src/component_parser.cpp:137:83: error: no matching function for call to ‘from_chars(const char* const&, const char*, double&)’`
```
/usr/include/c++/9/type_traits:2378:11: error: no type named ‘type’ in ‘struct std::enable_if<false, std::from_chars_result>’
 2378 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
```
And the build exits with error and fails.

Is there a problem with my setup (its minimal and clean), or is the underlying system packages causing a trouble?

**Comment by bmagyar** [comment]
Please use the foxy branch instead
