### ISSUE TITLE
How can I get the RCLCPP Logging information.

### ISSUE THREAD

**Issue by AmmarAlbakri** [ros-controls/ros2_control_demos#228]
I have successfully built and run the demo packages, I am trying to modify the diffbot_system.cpp but I can't see my code running, for now, I am just adding a few logging messages here and there configure(), start(), etc..

How can I see the output of these logs, and where?

**Comment by christophfroehlich** [comment]
How do you launch this hardware interface, with the provided launch file? Did you see the original log messages from the `RCLCPP_INFO` macros before you changed something?

**Comment by AmmarAlbakri** [comment]
The problem is solved, my mistake was the ros2_control tag where I was loading the wrong plugin. It is working now and I can see all the log messages.
