### ISSUE TITLE
Provide methods to stop controllers, and verify they are stopped

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control_demos#34]
This is a problem we've noticed with ros1_control. When transitioning from streaming commands (e.g. teleoperation or visual servoing) to trajectory planning, we need a way to verify that the robot has actually stopped.

Otherwise, the robot continues to move while the trajectory plan occurs, which makes the start state invalid and the trajectory will not execute.

**Comment by destogl** [comment]
not proper repository and maybe solved.
