### ISSUE TITLE
Could not contact service /controller_manager/load_controller

### ISSUE THREAD

**Issue by Shreejit-D** [ros-controls/ros2_control_demos#359]
Hello,
I am using gazebo_ros2_control to simulate a prismatic joint. PFA the urdf and yaml file -
**URDF**
`<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    

    <link name="base_link">

    </link>

    

    <joint name="elevatorB_joint" type="fixed">
        <parent link="base_link"/>
        <child link="elevatorB"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="elevatorB">
        <visual>
            <origin xyz="-0.66 0 0.75"/>
            <geometry>
                <box size="0.02 1.14 1.5"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="-0.66 0 0.75"/>
            <geometry>
                <box size="0.02 1.14 1.5"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1000" x="0.02" y="1.14" z="1.5">
            <origin xyz="-0.66 0 0.75" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="elevatorB">
        <material>Gazebo/White</material>
    </gazebo>
    
    

    <joint name="elevatorL_joint" type="fixed">
        <parent link="base_link"/>
        <child link="elevatorL"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="elevatorL">
        <visual>
            <origin xyz="0 -0.56 0.75"/>
            <geometry>
                <box size="1.32 0.02 1.5"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 -0.56 0.75"/>
            <geometry>
                <box size="1.32 0.02 1.5"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1000" x="1.32" y="0.02" z="1.5">
            <origin xyz="0 -0.56 0.75" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="elevatorL">
        <material>Gazebo/White</material>
    </gazebo>

     

    <joint name="elevatorR_joint" type="fixed">
        <parent link="base_link"/>
        <child link="elevatorR"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="elevatorR">
        <visual>
            <origin xyz="0 0.56 0.75"/>
            <geometry>
                <box size="1.32 0.02 1.5"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0.56 0.75"/>
            <geometry>
                <box size="1.32 0.02 1.5"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1000" x="1.32" y="0.02" z="1.5">
            <origin xyz="0 0.56 0.75" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="elevatorR">
        <material>Gazebo/White</material>
    </gazebo>

    
    
    <joint name="elevatorCar_joint" type="prismatic">
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="0.0" upper="1" velocity="0.5"/>
        <origin xyz="0 0 0"/>
        <parent link="base_link"/>
        <child link="elevatorCar"/>
    </joint>

    <link name="elevatorCar">
        <visual>
            <origin xyz="0 0 0.3"/>
            <geometry>
                <box size="1.32 1.1 0.02"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.3"/>
            <geometry>
                <box size="1.32 1.1 0.02"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="100" x="1.32" y="1.1" z="0.02">
            <origin xyz="0 0 0.3" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="elevatorCar">
        <material>Gazebo/Black</material>
    </gazebo>

    
    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        <joint name="elevatorCar_joint">
            <command_interface name="position">
                <param name="min">-10</param>
                <param name="max">10</param>
            </command_interface>
            <state_interface name="position">
                <param name="initial_value">1.0</param>
            </state_interface>
            <state_interface name="velocity"/>
            <state_interface name="effort"/>
        </joint>
    </ros2_control>

    <gazebo>
        <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
            <parameters>$(find bot_elevator)/config/elevator_controller.yaml</parameters>
        </plugin>
    </gazebo>

</robot>`

**<yaml>**
```
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - elevatorCar_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

```
Whenever I am launching the simulation with the launch file -
```
import os

from ament_index_python.packages import get_package_share_directory


from launch import LaunchDescription
from launch.actions import ExecuteProcess, IncludeLaunchDescription, RegisterEventHandler
from launch.event_handlers import OnProcessExit
from launch.launch_description_sources import PythonLaunchDescriptionSource

from launch_ros.actions import Node



def generate_launch_description():

    package_name='bot_elevator'

    rsp = IncludeLaunchDescription(
                PythonLaunchDescriptionSource([os.path.join(
                    get_package_share_directory(package_name),'launch','launch.py'
                )]), launch_arguments={'use_sim_time': 'true'}.items()
    )

    # Include the Gazebo launch file, provided by the gazebo_ros package
    gazebo = IncludeLaunchDescription(
                PythonLaunchDescriptionSource([os.path.join(
                    get_package_share_directory('gazebo_ros'), 'launch', 'gazebo.launch.py')]),
             )

    # Run the spawner node from the gazebo_ros package. The entity name doesn't really matter if you only have a single robot.
    spawn_entity = Node(package='gazebo_ros', executable='spawn_entity.py',
                        arguments=['-topic', 'robot_description',
                                   '-entity', 'my_bot'],
                        output='screen')

    # load_joint_state_controller = ExecuteProcess(
    #     cmd=['ros2', 'control', 'load_controller', '--set-state', 'active',
    #          'joint_state_broadcaster'],
    #     output='screen'
    # )

    # load_joint_trajectory_controller = ExecuteProcess(
    #     cmd=['ros2', 'control', 'load_controller', '--set-state', 'active',
    #          'joint_trajectory_controller'],
    #     output='screen'
    # )

    # Launch them all!
    return LaunchDescription([
        # RegisterEventHandler(
        #     event_handler=OnProcessExit(
        #         target_action=spawn_entity,
        #         on_exit=[load_joint_state_controller],
        #     )
        # ),
        # RegisterEventHandler(
        #     event_handler=OnProcessExit(
        #         target_action=load_joint_state_controller,
        #         on_exit=[load_joint_trajectory_controller],
        #     )
        # ),
        rsp,
        gazebo,
        spawn_entity,
    ])
```
    where I was trying to launch the simulation with load_controller or without load controller, later manually loading it (as mentioned in earlier solutions), I am getting the error Could not contact service /controller_manager/load_controller. Would appreciate some help regarding this issue.

**Comment by christophfroehlich** [comment]
I'll close this issue here, because it is not related to the ros2_control_demos repository. Please post your problem to https://robotics.stackexchange.com and add the console output of the launch file. Thanks!
