### ISSUE TITLE
Example executables from README are missing

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control_demos#38]
After building, these 2 demos don't exist:

`ros2 launch ros2_control_demo_robot demo_robot_launch.py`

`ros2 launch ros2_control_demo_robot demo_robot_modular_launch.py`

Build command:

`colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release`

**Comment by Karsten1987** [comment]
@destogl the launch files described in the readme don't seem to exist

**Comment by destogl** [comment]
@AndyZe sorry, the README was in the old state. I updated it just now...

**Comment by destogl** [comment]
obsolete.
