### ISSUE TITLE
Enhancing README.md

### ISSUE THREAD

**Issue by Nils-ChristianIseke** [ros-controls/ros2_control_demos#383]
The README.md file does not provide enough support for inexperienced users. This causes unnecessary issues / work for / by inexperienced users.
The README should at least refer to the necessary resources, better still have a step by step guide on how to run the examples from scratch.

**Comment by christophfroehlich** [comment]
The necessary information is inside the doc folder in rst syntax for https://control.ros.org/master/doc/ros2_control_demos/doc/index.html
I don't want to duplicate information actually.

But I see that there is a lack of an introduction in the readme.md pointing to the correct page on control.ros.org. Would this be sufficient?

**Comment by Nils-ChristianIseke** [comment]
How about #384?

**Comment by christophfroehlich** [comment]
closed with #384
