### ISSUE TITLE
get_name() doesn't seem to be virtual

### ISSUE THREAD

**Issue by dignakov** [ros-controls/ros2_control_demos#41]
I'm trying to compile the `add_rrbot_system_position_joints` branch, and I'm getting this error:

```
.../ros2_control_demos/ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_position_only.hpp:50:15: error: ‘std::string hardware_interface::BaseSystemHardwareInterface::get_name() const’ marked ‘final’, but is not virtual
```

If I remove `final` it seems to compile fine.

**Comment by destogl** [comment]
it should be now. check [here](https://github.com/ros-controls/ros2_control/pull/147/files#diff-04c36822f25b0598bc347395128f5d86R65v)
