### ISSUE TITLE
Demo not work

### ISSUE THREAD

**Issue by LuisYordano** [ros-controls/ros2_control_demos#42]
I'm testing demo -b add_rrbot_system_position_joints.

In the file rrbot_system_position_only.launch.py, exist line executable='ros2_control_node', but in the package control_manager **not exist ros2_control_node**.

![image](https://user-images.githubusercontent.com/13818395/94842035-8098fe80-03e0-11eb-9f3a-c0e746ebeb0f.png)

Could indicate the steps to run the demo correctly.

Thank you in advance.

**Comment by destogl** [comment]
Hi @LuisYordano,

thanks for your interest in the ros2_control.

The instructions are in the ros-controls/ros2_control#147  at the bottom of the [first post](https://github.com/ros-controls/ros2_control/pull/147#issue-487193575).

Please consider that the library is currently under heavy development, therefore the API could by broken at any time!

**Comment by LuisYordano** [comment]
Hi @destogl,

Thanks for the support.

Error testing demo : 

`[ERROR] [1601656357.549508851] [ControllerManager]: Loader for controller 'forward_command_controller_position' not found
`

![image](https://user-images.githubusercontent.com/13818395/94947886-fe720e00-04a3-11eb-80ca-c26c8a013846.png)

I have executed the code without making any modifications.

As the library is under development, I close this issue.

**Comment by destogl** [comment]
Did you sourced your environment after building the packages?

**Comment by LuisYordano** [comment]
Yes, I did.

Could indicate the links of the repositories that works for you?
