### ISSUE TITLE
Gazebo examples

### ISSUE THREAD

**Issue by C-monC** [ros-controls/ros2_control_demos#55]
Hi,

Are the gazebo files currently not on the repo? Searching for ros2_control_demo_hardware_gazebo returns nothing. 

Thanks,
Simon

**Comment by destogl** [comment]
Hi Simon,

no they are not. The gazebo support is currently in [development](https://discourse.ros.org/t/gazebo-support-for-ros2-control-breakout-session/18468). We should have this in the next 4-6 weeks.

**Comment by C-monC** [comment]
Okay cool, is tomorrow's meeting open? I am interested in helping.

**Comment by destogl** [comment]
> Okay cool, is tomorrow's meeting open? I am interested in helping.

Of course! You are very welcome to join! Also check the work for @ahcorde in the ros-simulation/gazebo_ros2_control#44

**Comment by C-monC** [comment]
Perfect, I'll definitely join. 
Are there some easier/smaller issues I can try? I haven't done much c++ apart from tutorials/courses.

**Comment by destogl** [comment]
If you want to start, look are issues marked with "good first issue" label. They are usually easy and straightforward
