### ISSUE TITLE
Create demo for example 3 : Industrial Robots with integrated sensor

### ISSUE THREAD

**Issue by bailaC** [ros-controls/ros2_control_demos#67]
I am working on the Example 3. 
https://github.com/ros-controls/roadmap/blob/master/design_drafts/components_architecture_and_urdf_examples.md#3-industrial-robots-with-integrated-sensor

**Comment by destogl** [comment]
Please consider also ros-controls/roadmap#32

**Comment by destogl** [comment]
done
