### ISSUE TITLE
Running this I get 

### ISSUE THREAD

**Issue by FirstCaptain** [ros-controls/ros2_control_demos#88]
I am seeing the following errors and the rrbot is failing to load in RVIZ after following instructions in the Readme

My System is Ubuntu 20.04 and I am running Ros2 Foxy. 

![Screenshot from 2021-04-28 11-22-44](https://user-images.githubusercontent.com/3292171/116438445-116b7780-a814-11eb-8385-2e38a0e54fc9.png)
![Screenshot from 2021-04-28 11-21-56](https://user-images.githubusercontent.com/3292171/116438361-fc8ee400-a813-11eb-98c2-89751a331fbe.png)

**Comment by Karsten1987** [comment]
I've encountered this as well and I feel we should update some documentation on this.

The system is not broken, it's just not fully activated yet. If you look into the launch file, we're launching a robot state publisher node. That node however needs a `joint_states` topic to be published on. For this to happen, we need to load and start the `joint_state_controller`, alternatively also called `joint_state_broadcaster`. 

All you have to do is to call the following in a second shell after you've launched your system:
```
ros2 control load_controller joint_state_controller --state start
```

**Comment by FirstCaptain** [comment]
Awesome thanks, that works

**Comment by bmagyar** [comment]
Let's keep this open until docs are updated

**Comment by destogl** [comment]
obsolete.
