### ISSUE TITLE
controller manager spawner.py bug

### ISSUE THREAD

**Issue by roboticsai** [ros-controls/ros2_control_demos#93]
After i run the command:
`ros2 launch ros2_control_demo_robot diffbot_system.launch.py`
i'm getting the errors:
`format [py]: __init__() got an unexpected keyword argument 'parameter'`
As i debugged the source code. The bug is comming form this line:
```
            Node(
                package="controller_manager",
                executable="spawner.py",
                parameter=["joint_state_controller"],
                output="screen",
            ),
```
from given launch file. 
When i change the parameter to the arguments it works fine but still got the warnnis that controller_manager is not available. 
It shows that controller manager in ros2 has some bugs.
Any way to solve this?

Environments;
1. Os: ubuntu 20.04 desktop
2. ros: ros2 foxy

**Comment by Gaurav-Kapoor-InMach** [comment]
@roboticsai I also got the same error. So i removed this node in the launch file and its was working fine for me. But there could be an error in spawner.py.
