### ISSUE TITLE
Multiple interfaces demo not updated

### ISSUE THREAD

**Issue by olivier-stasse** [ros-controls/ros2_control_demos#95]
Status
-------
The current `ros2_control_demo_robot/description/rrbot_system_multi_interface.urdf.xacro` in https://github.com/ros-controls/ros2_control_demos/blob/f5e163d4e0554c1f7c3ec0fb4629ae3e2be2555d/ros2_control_demo_robot/description/rrbot_system_multi_interface.urdf.xacro#L10 points towards the wrong location of `rrbot.urdf.xacro`. It is the same for `rrbot.gazebo.xacro ` and for `rrbot.materials.xacro`

They are either in the `rrbot` or `gazebo` directories.
A PR for fixing it is under way.

**Comment by christophfroehlich** [comment]
This was fixed with #76
